<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260112160213 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE custom_id_format (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, elements JSON NOT NULL, version INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, inventory_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B2B7B0949EEA759 ON custom_id_format (inventory_id)');
        $this->addSql('CREATE TABLE inventory (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, category VARCHAR(50) NOT NULL, image_url VARCHAR(255) DEFAULT NULL, is_public BOOLEAN NOT NULL, version INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, creator_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_inventory_creator ON inventory (creator_id)');
        $this->addSql('CREATE TABLE inventory_has_tag (inventory_id INT NOT NULL, inventory_tag_id INT NOT NULL, PRIMARY KEY (inventory_id, inventory_tag_id))');
        $this->addSql('CREATE INDEX IDX_764D4C859EEA759 ON inventory_has_tag (inventory_id)');
        $this->addSql('CREATE INDEX IDX_764D4C85BA0EFFBA ON inventory_has_tag (inventory_tag_id)');
        $this->addSql('CREATE TABLE inventory_access (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, can_write BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, inventory_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6B5B7FF9EEA759 ON inventory_access (inventory_id)');
        $this->addSql('CREATE INDEX IDX_6B5B7FFA76ED395 ON inventory_access (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ACCESS ON inventory_access (inventory_id, user_id)');
        $this->addSql('CREATE TABLE inventory_discussion_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, inventory_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D5914059EEA759 ON inventory_discussion_post (inventory_id)');
        $this->addSql('CREATE INDEX IDX_D591405A76ED395 ON inventory_discussion_post (user_id)');
        $this->addSql('CREATE INDEX idx_discussion_inventory ON inventory_discussion_post (inventory_id, created_at)');
        $this->addSql('CREATE TABLE inventory_field (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, field_name VARCHAR(100) NOT NULL, field_type VARCHAR(50) NOT NULL, field_order INT NOT NULL, show_in_table BOOLEAN NOT NULL, description TEXT DEFAULT NULL, is_required BOOLEAN NOT NULL, field_data JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, inventory_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8769EE589EEA759 ON inventory_field (inventory_id)');
        $this->addSql('CREATE TABLE inventory_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, custom_id VARCHAR(255) NOT NULL, version INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, inventory_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_item_inventory ON inventory_item (inventory_id)');
        $this->addSql('CREATE INDEX idx_item_created_by ON inventory_item (created_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INVENTORY_CUSTOM_ID ON inventory_item (inventory_id, custom_id)');
        $this->addSql('CREATE TABLE inventory_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_TAG_NAME ON inventory_tag (name)');
        $this->addSql('CREATE TABLE item_field_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, item_id INT NOT NULL, field_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D6B896F9126F525E ON item_field_value (item_id)');
        $this->addSql('CREATE INDEX IDX_D6B896F9443707B0 ON item_field_value (field_id)');
        $this->addSql('CREATE TABLE item_like (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, item_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_64530448126F525E ON item_like (item_id)');
        $this->addSql('CREATE INDEX IDX_64530448A76ED395 ON item_like (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ITEM_USER_LIKE ON item_like (item_id, user_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(255) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, language VARCHAR(5) NOT NULL, theme VARCHAR(10) NOT NULL, is_active BOOLEAN NOT NULL, is_blocked BOOLEAN NOT NULL, is_admin BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, social_provider VARCHAR(255) DEFAULT NULL, social_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE custom_id_format ADD CONSTRAINT FK_B2B7B0949EEA759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory ADD CONSTRAINT FK_B12D4A3661220EA6 FOREIGN KEY (creator_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_has_tag ADD CONSTRAINT FK_764D4C859EEA759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_has_tag ADD CONSTRAINT FK_764D4C85BA0EFFBA FOREIGN KEY (inventory_tag_id) REFERENCES inventory_tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inventory_access ADD CONSTRAINT FK_6B5B7FF9EEA759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_access ADD CONSTRAINT FK_6B5B7FFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_discussion_post ADD CONSTRAINT FK_D5914059EEA759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_discussion_post ADD CONSTRAINT FK_D591405A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_field ADD CONSTRAINT FK_8769EE589EEA759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_item ADD CONSTRAINT FK_55BDEA309EEA759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_item ADD CONSTRAINT FK_55BDEA30B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE item_field_value ADD CONSTRAINT FK_D6B896F9126F525E FOREIGN KEY (item_id) REFERENCES inventory_item (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE item_field_value ADD CONSTRAINT FK_D6B896F9443707B0 FOREIGN KEY (field_id) REFERENCES inventory_field (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE item_like ADD CONSTRAINT FK_64530448126F525E FOREIGN KEY (item_id) REFERENCES inventory_item (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE item_like ADD CONSTRAINT FK_64530448A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE custom_id_format DROP CONSTRAINT FK_B2B7B0949EEA759');
        $this->addSql('ALTER TABLE inventory DROP CONSTRAINT FK_B12D4A3661220EA6');
        $this->addSql('ALTER TABLE inventory_has_tag DROP CONSTRAINT FK_764D4C859EEA759');
        $this->addSql('ALTER TABLE inventory_has_tag DROP CONSTRAINT FK_764D4C85BA0EFFBA');
        $this->addSql('ALTER TABLE inventory_access DROP CONSTRAINT FK_6B5B7FF9EEA759');
        $this->addSql('ALTER TABLE inventory_access DROP CONSTRAINT FK_6B5B7FFA76ED395');
        $this->addSql('ALTER TABLE inventory_discussion_post DROP CONSTRAINT FK_D5914059EEA759');
        $this->addSql('ALTER TABLE inventory_discussion_post DROP CONSTRAINT FK_D591405A76ED395');
        $this->addSql('ALTER TABLE inventory_field DROP CONSTRAINT FK_8769EE589EEA759');
        $this->addSql('ALTER TABLE inventory_item DROP CONSTRAINT FK_55BDEA309EEA759');
        $this->addSql('ALTER TABLE inventory_item DROP CONSTRAINT FK_55BDEA30B03A8386');
        $this->addSql('ALTER TABLE item_field_value DROP CONSTRAINT FK_D6B896F9126F525E');
        $this->addSql('ALTER TABLE item_field_value DROP CONSTRAINT FK_D6B896F9443707B0');
        $this->addSql('ALTER TABLE item_like DROP CONSTRAINT FK_64530448126F525E');
        $this->addSql('ALTER TABLE item_like DROP CONSTRAINT FK_64530448A76ED395');
        $this->addSql('DROP TABLE custom_id_format');
        $this->addSql('DROP TABLE inventory');
        $this->addSql('DROP TABLE inventory_has_tag');
        $this->addSql('DROP TABLE inventory_access');
        $this->addSql('DROP TABLE inventory_discussion_post');
        $this->addSql('DROP TABLE inventory_field');
        $this->addSql('DROP TABLE inventory_item');
        $this->addSql('DROP TABLE inventory_tag');
        $this->addSql('DROP TABLE item_field_value');
        $this->addSql('DROP TABLE item_like');
        $this->addSql('DROP TABLE "user"');
    }
}
