<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260114105913 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE item_field_value DROP CONSTRAINT fk_d6b896f9126f525e');
        $this->addSql('ALTER TABLE item_field_value DROP CONSTRAINT fk_d6b896f9443707b0');
        $this->addSql('DROP TABLE item_field_value');
        $this->addSql('ALTER TABLE custom_id_format ALTER version SET DEFAULT 1');
        $this->addSql('ALTER TABLE inventory ALTER version SET DEFAULT 1');
        $this->addSql('ALTER TABLE inventory_field ADD storage_slot VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX unique_field_name_inv ON inventory_field (inventory_id, field_name)');
        $this->addSql('CREATE UNIQUE INDEX unique_storage_slot_inv ON inventory_field (inventory_id, storage_slot)');
        $this->addSql('ALTER TABLE inventory_item DROP CONSTRAINT fk_55bdea30b03a8386');
        $this->addSql('ALTER TABLE inventory_item ADD text1 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD text2 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD text3 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD textarea1 TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD textarea2 TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD textarea3 TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD number1 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD number2 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD number3 DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD bool1 BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD bool2 BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD bool3 BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD link1 VARCHAR(1024) DEFAULT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD link2 VARCHAR(1024) DEFAULT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD link3 VARCHAR(1024) DEFAULT NULL');
        $this->addSql('ALTER TABLE inventory_item DROP version');
        $this->addSql('ALTER TABLE inventory_item ALTER custom_id TYPE VARCHAR(64)');
        $this->addSql('ALTER TABLE inventory_item ALTER created_by_id DROP NOT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD CONSTRAINT FK_55BDEA30B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_item_created_by RENAME TO IDX_55BDEA30B03A8386');
        $this->addSql('ALTER INDEX uniq_inventory_custom_id RENAME TO uniq_item_custom_id');
        $this->addSql('ALTER INDEX uniq_tag_name RENAME TO UNIQ_7AE3D8E75E237E06');
        $this->addSql('ALTER TABLE item_like DROP CONSTRAINT fk_64530448a76ed395');
        $this->addSql('ALTER TABLE item_like ADD CONSTRAINT FK_64530448A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE item_field_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, item_id INT NOT NULL, field_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_d6b896f9443707b0 ON item_field_value (field_id)');
        $this->addSql('CREATE INDEX idx_d6b896f9126f525e ON item_field_value (item_id)');
        $this->addSql('ALTER TABLE item_field_value ADD CONSTRAINT fk_d6b896f9126f525e FOREIGN KEY (item_id) REFERENCES inventory_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_field_value ADD CONSTRAINT fk_d6b896f9443707b0 FOREIGN KEY (field_id) REFERENCES inventory_field (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE custom_id_format ALTER version DROP DEFAULT');
        $this->addSql('ALTER TABLE inventory ALTER version DROP DEFAULT');
        $this->addSql('DROP INDEX unique_field_name_inv');
        $this->addSql('DROP INDEX unique_storage_slot_inv');
        $this->addSql('ALTER TABLE inventory_field DROP storage_slot');
        $this->addSql('ALTER TABLE inventory_item DROP CONSTRAINT FK_55BDEA30B03A8386');
        $this->addSql('ALTER TABLE inventory_item ADD version INT NOT NULL');
        $this->addSql('ALTER TABLE inventory_item DROP text1');
        $this->addSql('ALTER TABLE inventory_item DROP text2');
        $this->addSql('ALTER TABLE inventory_item DROP text3');
        $this->addSql('ALTER TABLE inventory_item DROP textarea1');
        $this->addSql('ALTER TABLE inventory_item DROP textarea2');
        $this->addSql('ALTER TABLE inventory_item DROP textarea3');
        $this->addSql('ALTER TABLE inventory_item DROP number1');
        $this->addSql('ALTER TABLE inventory_item DROP number2');
        $this->addSql('ALTER TABLE inventory_item DROP number3');
        $this->addSql('ALTER TABLE inventory_item DROP bool1');
        $this->addSql('ALTER TABLE inventory_item DROP bool2');
        $this->addSql('ALTER TABLE inventory_item DROP bool3');
        $this->addSql('ALTER TABLE inventory_item DROP link1');
        $this->addSql('ALTER TABLE inventory_item DROP link2');
        $this->addSql('ALTER TABLE inventory_item DROP link3');
        $this->addSql('ALTER TABLE inventory_item ALTER custom_id TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE inventory_item ALTER created_by_id SET NOT NULL');
        $this->addSql('ALTER TABLE inventory_item ADD CONSTRAINT fk_55bdea30b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_55bdea30b03a8386 RENAME TO idx_item_created_by');
        $this->addSql('ALTER INDEX uniq_item_custom_id RENAME TO uniq_inventory_custom_id');
        $this->addSql('ALTER INDEX uniq_7ae3d8e75e237e06 RENAME TO uniq_tag_name');
        $this->addSql('ALTER TABLE item_like DROP CONSTRAINT FK_64530448A76ED395');
        $this->addSql('ALTER TABLE item_like ADD CONSTRAINT fk_64530448a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
