<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;


final class Version20260121182651 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {

        if (!$schema->hasTable('api_token')) {
            $this->addSql('CREATE TABLE api_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, description VARCHAR(255) DEFAULT NULL, inventory_id INT NOT NULL, PRIMARY KEY (id))');
        }
        

        if ($schema->hasTable('api_token')) {
            $apiTokenTable = $schema->getTable('api_token');
            if (!$apiTokenTable->hasIndex('UNIQ_7BA2F5EB5F37A13B')) {
                $this->addSql('CREATE UNIQUE INDEX UNIQ_7BA2F5EB5F37A13B ON api_token (token)');
            }
            if (!$apiTokenTable->hasIndex('IDX_7BA2F5EB9EEA759')) {
                $this->addSql('CREATE INDEX IDX_7BA2F5EB9EEA759 ON api_token (inventory_id)');
            }
            if (!$apiTokenTable->hasForeignKey('FK_7BA2F5EB9EEA759')) {
                $this->addSql('ALTER TABLE api_token ADD CONSTRAINT FK_7BA2F5EB9EEA759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) NOT DEFERRABLE');
            }
        }
        

        if ($schema->hasTable('inventory_api_token')) {
            $invApiTable = $schema->getTable('inventory_api_token');
            if ($invApiTable->hasForeignKey('fk_fc1e1c839eea759')) {
                $this->addSql('ALTER TABLE inventory_api_token DROP CONSTRAINT fk_fc1e1c839eea759');
            }
            if ($invApiTable->hasForeignKey('fk_fc1e1c83b03a8386')) {
                $this->addSql('ALTER TABLE inventory_api_token DROP CONSTRAINT fk_fc1e1c83b03a8386');
            }
            $this->addSql('DROP TABLE inventory_api_token');
        }
        

        if ($schema->hasTable('salesforce_integration')) {
            $sfTable = $schema->getTable('salesforce_integration');
            if ($sfTable->hasForeignKey('fk_fa1f243ba76ed395')) {
                $this->addSql('ALTER TABLE salesforce_integration DROP CONSTRAINT fk_fa1f243ba76ed395');
            }
            $this->addSql('DROP TABLE salesforce_integration');
        }
        
        if ($schema->hasTable('support_ticket')) {
            $ticketTable = $schema->getTable('support_ticket');
            if ($ticketTable->hasForeignKey('fk_1f5a4d5371ce806')) {
                $this->addSql('ALTER TABLE support_ticket DROP CONSTRAINT fk_1f5a4d5371ce806');
            }
            if ($ticketTable->hasForeignKey('fk_1f5a4d539eea759')) {
                $this->addSql('ALTER TABLE support_ticket DROP CONSTRAINT fk_1f5a4d539eea759');
            }
            $this->addSql('DROP TABLE support_ticket');
        }
        
        if ($schema->hasTable('inventory_discussion_post')) {
            $discTable = $schema->getTable('inventory_discussion_post');
            
            if ($discTable->hasForeignKey('fk_d5914059eea759')) {
                $this->addSql('ALTER TABLE inventory_discussion_post DROP CONSTRAINT fk_d5914059eea759');
            }
            if ($discTable->hasForeignKey('fk_d591405f675f31b')) {
                $this->addSql('ALTER TABLE inventory_discussion_post DROP CONSTRAINT fk_d591405f675f31b');
            }
            
            if ($discTable->hasIndex('idx_d591405f675f31b')) {
                $this->addSql('DROP INDEX idx_d591405f675f31b');
            }
            

            if ($discTable->hasColumn('author_id') && !$discTable->hasColumn('user_id')) {
                $this->addSql('ALTER TABLE inventory_discussion_post RENAME COLUMN author_id TO user_id');
            }
            
            if (!$discTable->hasForeignKey('FK_D5914059EEA759')) {
                $this->addSql('ALTER TABLE inventory_discussion_post ADD CONSTRAINT FK_D5914059EEA759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE NOT DEFERRABLE');
            }
            if (!$discTable->hasForeignKey('FK_D591405A76ED395')) {
                $this->addSql('ALTER TABLE inventory_discussion_post ADD CONSTRAINT FK_D591405A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
            }
            
            if (!$discTable->hasIndex('IDX_D591405A76ED395')) {
                $this->addSql('CREATE INDEX IDX_D591405A76ED395 ON inventory_discussion_post (user_id)');
            }
            if (!$discTable->hasIndex('idx_discussion_inventory')) {
                $this->addSql('CREATE INDEX idx_discussion_inventory ON inventory_discussion_post (inventory_id, created_at)');
            }
        }
        
        if ($schema->hasTable('inventory_field')) {
            $fieldTable = $schema->getTable('inventory_field');
            
            if ($fieldTable->hasColumn('field_name')) {
                $this->addSql('ALTER TABLE inventory_field ALTER field_name TYPE VARCHAR(100)');
            }
            if ($fieldTable->hasColumn('storage_slot')) {
                $this->addSql('ALTER TABLE inventory_field ALTER storage_slot TYPE VARCHAR(20)');
            }
            
            if (!$fieldTable->hasIndex('unique_field_name_inv')) {
                $this->addSql('CREATE UNIQUE INDEX unique_field_name_inv ON inventory_field (inventory_id, field_name)');
            }
            if (!$fieldTable->hasIndex('unique_storage_slot_inv')) {
                $this->addSql('CREATE UNIQUE INDEX unique_storage_slot_inv ON inventory_field (inventory_id, storage_slot)');
            }
        }
        
        if ($schema->hasTable('inventory_item')) {
            $itemTable = $schema->getTable('inventory_item');
            
            if ($itemTable->hasForeignKey('fk_55bdea309eea759')) {
                $this->addSql('ALTER TABLE inventory_item DROP CONSTRAINT fk_55bdea309eea759');
            }
            if ($itemTable->hasForeignKey('fk_55bdea30b03a8386')) {
                $this->addSql('ALTER TABLE inventory_item DROP CONSTRAINT fk_55bdea30b03a8386');
            }
            
            if ($itemTable->hasColumn('custom_id')) {
                $this->addSql('ALTER TABLE inventory_item ALTER custom_id TYPE VARCHAR(64)');
                $this->addSql('ALTER TABLE inventory_item ALTER custom_id SET NOT NULL');
            }
            if ($itemTable->hasColumn('link1')) {
                $this->addSql('ALTER TABLE inventory_item ALTER link1 TYPE VARCHAR(1024)');
            }
            if ($itemTable->hasColumn('link2')) {
                $this->addSql('ALTER TABLE inventory_item ALTER link2 TYPE VARCHAR(1024)');
            }
            if ($itemTable->hasColumn('link3')) {
                $this->addSql('ALTER TABLE inventory_item ALTER link3 TYPE VARCHAR(1024)');
            }
            
            if (!$itemTable->hasForeignKey('FK_55BDEA309EEA759')) {
                $this->addSql('ALTER TABLE inventory_item ADD CONSTRAINT FK_55BDEA309EEA759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE NOT DEFERRABLE');
            }
            if (!$itemTable->hasForeignKey('FK_55BDEA30B03A8386')) {
                $this->addSql('ALTER TABLE inventory_item ADD CONSTRAINT FK_55BDEA30B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
            }
            
            if (!$itemTable->hasIndex('uniq_item_custom_id')) {
                $this->addSql('CREATE UNIQUE INDEX uniq_item_custom_id ON inventory_item (inventory_id, custom_id)');
            }
            

            if ($itemTable->hasIndex('idx_55bdea309eea759') && !$itemTable->hasIndex('idx_item_inventory')) {
                $this->addSql('ALTER INDEX idx_55bdea309eea759 RENAME TO idx_item_inventory');
            }
        }
        
 
        if ($schema->hasTable('item_like')) {
            $likeTable = $schema->getTable('item_like');
            

            if ($likeTable->hasForeignKey('fk_64530448126f525e')) {
                $this->addSql('ALTER TABLE item_like DROP CONSTRAINT fk_64530448126f525e');
            }
            if ($likeTable->hasForeignKey('fk_64530448a76ed395')) {
                $this->addSql('ALTER TABLE item_like DROP CONSTRAINT fk_64530448a76ed395');
            }
            

            if (!$likeTable->hasForeignKey('FK_64530448126F525E')) {
                $this->addSql('ALTER TABLE item_like ADD CONSTRAINT FK_64530448126F525E FOREIGN KEY (item_id) REFERENCES inventory_item (id) ON DELETE CASCADE NOT DEFERRABLE');
            }
            if (!$likeTable->hasForeignKey('FK_64530448A76ED395')) {
                $this->addSql('ALTER TABLE item_like ADD CONSTRAINT FK_64530448A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
            }
            
            if (!$likeTable->hasIndex('UNIQ_ITEM_USER_LIKE')) {
                $this->addSql('CREATE UNIQUE INDEX UNIQ_ITEM_USER_LIKE ON item_like (item_id, user_id)');
            }
        }
        
        if ($schema->hasTable('"user"')) {
            $userTable = $schema->getTable('"user"');
            
            if ($userTable->hasColumn('password')) {
                $this->addSql('ALTER TABLE "user" ALTER password DROP NOT NULL');
            }
            if ($userTable->hasColumn('language')) {
                $this->addSql('ALTER TABLE "user" ALTER language TYPE VARCHAR(5)');
            }
            if ($userTable->hasColumn('social_provider')) {
                $this->addSql('ALTER TABLE "user" ALTER social_provider TYPE VARCHAR(255)');
            }
            
            if ($userTable->hasIndex('uniq_8d93d649e7927c74') && !$userTable->hasIndex('UNIQ_EMAIL')) {
                $this->addSql('ALTER INDEX uniq_8d93d649e7927c74 RENAME TO UNIQ_EMAIL');
            }
        }
    }

    public function down(Schema $schema): void
    {
        if (!$schema->hasTable('inventory_api_token')) {
            $this->addSql('CREATE TABLE inventory_api_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, usage_count INT NOT NULL, inventory_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
            $this->addSql('CREATE UNIQUE INDEX uniq_fc1e1c835f37a13b ON inventory_api_token (token)');
            $this->addSql('CREATE INDEX idx_fc1e1c83b03a8386 ON inventory_api_token (created_by_id)');
            $this->addSql('CREATE INDEX idx_fc1e1c839eea759 ON inventory_api_token (inventory_id)');
            $this->addSql('ALTER TABLE inventory_api_token ADD CONSTRAINT fk_fc1e1c839eea759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
            $this->addSql('ALTER TABLE inventory_api_token ADD CONSTRAINT fk_fc1e1c83b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        }
        
        if (!$schema->hasTable('salesforce_integration')) {
            $this->addSql('CREATE TABLE salesforce_integration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, salesforce_account_id VARCHAR(255) DEFAULT NULL, salesforce_contact_id VARCHAR(255) DEFAULT NULL, company VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, state VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(50) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, industry VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, number_of_employees INT DEFAULT NULL, annual_revenue NUMERIC(15, 2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, synced_to_salesforce BOOLEAN NOT NULL, last_sync_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
            $this->addSql('CREATE UNIQUE INDEX uniq_fa1f243ba76ed395 ON salesforce_integration (user_id)');
            $this->addSql('ALTER TABLE salesforce_integration ADD CONSTRAINT fk_fa1f243ba76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        }
        
        if (!$schema->hasTable('support_ticket')) {
            $this->addSql('CREATE TABLE support_ticket (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, summary VARCHAR(255) NOT NULL, description TEXT NOT NULL, priority VARCHAR(20) NOT NULL, link VARCHAR(255) NOT NULL, json_file_path VARCHAR(255) DEFAULT NULL, uploaded_to_cloud BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reported_by_id INT NOT NULL, inventory_id INT DEFAULT NULL, PRIMARY KEY (id))');
            $this->addSql('CREATE INDEX idx_1f5a4d5371ce806 ON support_ticket (reported_by_id)');
            $this->addSql('CREATE INDEX idx_1f5a4d539eea759 ON support_ticket (inventory_id)');
            $this->addSql('ALTER TABLE support_ticket ADD CONSTRAINT fk_1f5a4d5371ce806 FOREIGN KEY (reported_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
            $this->addSql('ALTER TABLE support_ticket ADD CONSTRAINT fk_1f5a4d539eea759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        }
        
        if ($schema->hasTable('api_token')) {
            $apiTable = $schema->getTable('api_token');
            if ($apiTable->hasForeignKey('FK_7BA2F5EB9EEA759')) {
                $this->addSql('ALTER TABLE api_token DROP CONSTRAINT FK_7BA2F5EB9EEA759');
            }
            $this->addSql('DROP TABLE api_token');
        }
        
        if ($schema->hasTable('inventory_discussion_post')) {
            $discTable = $schema->getTable('inventory_discussion_post');
            if ($discTable->hasForeignKey('FK_D5914059EEA759')) {
                $this->addSql('ALTER TABLE inventory_discussion_post DROP CONSTRAINT FK_D5914059EEA759');
            }
            if ($discTable->hasForeignKey('FK_D591405A76ED395')) {
                $this->addSql('ALTER TABLE inventory_discussion_post DROP CONSTRAINT FK_D591405A76ED395');
            }
            if ($discTable->hasIndex('IDX_D591405A76ED395')) {
                $this->addSql('DROP INDEX IDX_D591405A76ED395');
            }
            if ($discTable->hasIndex('idx_discussion_inventory')) {
                $this->addSql('DROP INDEX idx_discussion_inventory');
            }
            if ($discTable->hasColumn('user_id') && !$discTable->hasColumn('author_id')) {
                $this->addSql('ALTER TABLE inventory_discussion_post RENAME COLUMN user_id TO author_id');
            }
            if (!$discTable->hasForeignKey('fk_d5914059eea759')) {
                $this->addSql('ALTER TABLE inventory_discussion_post ADD CONSTRAINT fk_d5914059eea759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
            }
            if (!$discTable->hasForeignKey('fk_d591405f675f31b')) {
                $this->addSql('ALTER TABLE inventory_discussion_post ADD CONSTRAINT fk_d591405f675f31b FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
            }
            if (!$discTable->hasIndex('idx_d591405f675f31b')) {
                $this->addSql('CREATE INDEX idx_d591405f675f31b ON inventory_discussion_post (author_id)');
            }
        }
        
        if ($schema->hasTable('inventory_field')) {
            $this->addSql('DROP INDEX unique_field_name_inv');
            $this->addSql('DROP INDEX unique_storage_slot_inv');
            $this->addSql('ALTER TABLE inventory_field ALTER field_name TYPE VARCHAR(255)');
            $this->addSql('ALTER TABLE inventory_field ALTER storage_slot TYPE VARCHAR(50)');
        }
        
        if ($schema->hasTable('inventory_item')) {
            $itemTable = $schema->getTable('inventory_item');
            if ($itemTable->hasForeignKey('FK_55BDEA309EEA759')) {
                $this->addSql('ALTER TABLE inventory_item DROP CONSTRAINT FK_55BDEA309EEA759');
            }
            if ($itemTable->hasForeignKey('FK_55BDEA30B03A8386')) {
                $this->addSql('ALTER TABLE inventory_item DROP CONSTRAINT FK_55BDEA30B03A8386');
            }
            $this->addSql('DROP INDEX uniq_item_custom_id');
            $this->addSql('ALTER TABLE inventory_item ALTER custom_id TYPE VARCHAR(255)');
            $this->addSql('ALTER TABLE inventory_item ALTER custom_id DROP NOT NULL');
            $this->addSql('ALTER TABLE inventory_item ALTER link1 TYPE VARCHAR(255)');
            $this->addSql('ALTER TABLE inventory_item ALTER link2 TYPE VARCHAR(255)');
            $this->addSql('ALTER TABLE inventory_item ALTER link3 TYPE VARCHAR(255)');
            $this->addSql('ALTER TABLE inventory_item ADD CONSTRAINT fk_55bdea309eea759 FOREIGN KEY (inventory_id) REFERENCES inventory (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
            $this->addSql('ALTER TABLE inventory_item ADD CONSTRAINT fk_55bdea30b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
            $this->addSql('ALTER INDEX idx_item_inventory RENAME TO idx_55bdea309eea759');
        }
        
        if ($schema->hasTable('item_like')) {
            $likeTable = $schema->getTable('item_like');
            if ($likeTable->hasForeignKey('FK_64530448126F525E')) {
                $this->addSql('ALTER TABLE item_like DROP CONSTRAINT FK_64530448126F525E');
            }
            if ($likeTable->hasForeignKey('FK_64530448A76ED395')) {
                $this->addSql('ALTER TABLE item_like DROP CONSTRAINT FK_64530448A76ED395');
            }
            $this->addSql('DROP INDEX UNIQ_ITEM_USER_LIKE');
            $this->addSql('ALTER TABLE item_like ADD CONSTRAINT fk_64530448126f525e FOREIGN KEY (item_id) REFERENCES inventory_item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
            $this->addSql('ALTER TABLE item_like ADD CONSTRAINT fk_64530448a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        }
    }
}
